# Introduction

# Equations

# Numerical Methods

In [3]:
#EAS 4610 proj
#crank-nicolson method 

# import packages
import numpy as np
import matplotlib.pyplot as plt
import pylab as py
import os
import math
from scipy.sparse import spdiags
#import xarray as xr

# parameters 
k = 2 #m/d
n = 0.2 #effective porosity 
S = 0 #storage coefficient 
H = 45 #m
zb = -45 #bottom of the aquifer
zt = 0 #top of the aquifer
L = 1000 #m, length of cross section
W = 1 #width of cross section normal to the plane of flow
vs = 0.025 #dimensionless density 
# ditch is located 590 m from the coastline at x = 0
h0 = 0.05 #m


# defining boundary conditions
Q0 = 0.1 #m**2/d - outflow, uniform flow towards the coast
Q0p = 0.05 #m**2/d - outflow when water is pumped from the ditch
zeta0 = -Q0/(k*vs) #m - boundary condition at the coast - top 
zeta0p = -Q0p/(k*vs) 
# at x=0, h0 = 0.05 m and zeta0 = -2 m
# at t=0, Q = -0.05 m**2/d
zetaf = -h0/vs  #steady state condition, end of simulation


# discretizing
x = np.linspace(0,L,L+1)
dx = 10 #m
t = np.linspace(0,100,200)
dt = 0.5 #yr

#courant number 
# no diffusion number?
D = 1
CD = (D*dt)/(dx**2)

#n should be the length of the spatial dimension
n = len(x)


data_hi1 = np.array([-0.5*CD*np.ones(L+1), (1+CD)*np.ones(L+1), -0.5*CD*np.ones(L+1)])
diags1 = np.array([-1,0,1])
hi1 = spdiags(data_hi1,diags1,L-1,L-1).toarray()
#above coeff matrix: is it needed? prob not

data_hi = np.array([0.5*CD*np.ones(L+1), (1-CD)*np.ones(L+1), 0.5*CD*np.ones(L+1)])
diags2 = np.array([-1,0,1])
hi = spdiags(data_hi,diags2,L-1,L-1).toarray()


data_zetai1 = np.array([-0.5*CD*np.ones(L+1), (1+CD)*np.ones(L+1), -0.5*CD*np.ones(L+1)])
diags3 = np.array([-1,0,1])
zetai1 = spdiags(data_zetai1,diags3,L-1,L-1).toarray()

data_zetai = np.array([0.5*CD*np.ones(L+1), (1-CD)*np.ones(L+1), 0.5*CD*np.ones(L+1)])
diags4 = np.array([-1,0,1])
zetai = spdiags(data_zetai,diags4,L-1,L-1).toarray()


hi1 = np.zeros((L-1,200))
zeta = np.zeros((L-1,200))  #given values matrix for zeta
hmat = np.zeros((L-1,200))  #given values matrix for h


#hi1[:,0] = 10 ##CHANGE THIS VALUE, JUST A PLACEHOLDER, INITIAL CONDITION HERE
hmat[0,:] = h0
zeta[0,:] = zeta0
zeta[-1,:] = zetaf

print((zeta))
for i in range(0,len(t)-1):
  #  zetai1[:,i+1] = np.linalg.inv(hi1)@(hi@zetai1[:,i]+(0.5*CD)*zeta[:,i]-(-0.5*CD)*zeta[:,i+1])
    hi1[:,i+1] = np.linalg.inv(zetai1)@(zetai@hi1[:,i]+(0.5*CD)*hmat[:,i]-(-0.5*CD)*hmat[:,i+1])
print(hi1)
'''
#creating the known matrices
#M**(k+1)
bins = np.array([-1/2*Cd*np.ones(n),(1+Cd)*np.ones(n),-1/2*Cd*np.ones(n)])
diags = np.array([-1,0,1])
M_k1 = spdiags(bins,diags,n,n).toarray()

#M**k
bins2 = np.array([1/2*Cd*np.ones(n),(1-Cd)*np.ones(n),1/2*Cd*np.ones(n)])
M_k = spdiags(bins2,diags,n,n).toarray()

#A
A = np.ones(n,len(t))
A[1,:] = zeta0_a
A[-1,:] = zeta0_b
'''

[[-2. -2. -2. ... -2. -2. -2.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [-2. -2. -2. ... -2. -2. -2.]]
[[0.00000000e+00 2.48757758e-04 4.95046442e-04 ... 2.36483270e-02
  2.37029150e-02 2.37571928e-02]
 [0.00000000e+00 6.18804223e-07 2.46293286e-06 ... 8.24543849e-03
  8.29227982e-03 8.33903279e-03]
 [0.00000000e+00 1.53932351e-09 9.19010485e-09 ... 2.21963311e-03
  2.24109552e-03 2.26261087e-03]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]]


'\n#creating the known matrices\n#M**(k+1)\nbins = np.array([-1/2*Cd*np.ones(n),(1+Cd)*np.ones(n),-1/2*Cd*np.ones(n)])\ndiags = np.array([-1,0,1])\nM_k1 = spdiags(bins,diags,n,n).toarray()\n\n#M**k\nbins2 = np.array([1/2*Cd*np.ones(n),(1-Cd)*np.ones(n),1/2*Cd*np.ones(n)])\nM_k = spdiags(bins2,diags,n,n).toarray()\n\n#A\nA = np.ones(n,len(t))\nA[1,:] = zeta0_a\nA[-1,:] = zeta0_b\n'

# Results

# Figures 

# Video Walkthrough

# References
Bakker, M. (1970, January 1). Simple groundwater flow models for seawater intrusion: Semantic scholar. undefined. Retrieved November 27, 2022, from https://www.semanticscholar.org/paper/SIMPLE-GROUNDWATER-FLOW-MODELS-FOR-SEAWATER-Bakker/1ac46ef8707dda37496dd907e3dc9e3b0d52c4bc 